server:
  port: 8083  #服务端口配置
spring:
  servlet:
    multipart:
      max-file-size: 300MB  #上传文件最大值
      max-request-size: 300MB #请求消息最大值
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #数据源配置
    url: jdbc:mysql://127.0.0.1:3306/ms_base_db?serverTimezone=Asia/Shanghai
    username: root
    password: mn@123456!
    type: com.alibaba.druid.pool.DruidDataSource  #连接池配置
    max-idle: 10  #No operations allowed after connection closed错误原因及解决
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
  redis:
    host: 127.0.0.1 #redis服务器地址
    port: 6379
    password: mn@123456!
    timeout: 10000ms #超时时间
    database: 0 #0-15 16个库 默认0
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-wait: -1ms #默认-1 最大连接阻塞等待时间
        max-idle: 8 #最大空闲连接 默认8
        min-idle: 0 #最小空闲连接
  profiles:
    active: dao
  application:
    name: microservice-base #服务名称-服务之间使用名称进行通讯

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka #填写注册中心服务器地址
    register-with-eureka: true  #是否需要将自己注册到注册中心
    fetch-registry: true  #是否需要搜索服务信息
  instance:
    prefer-ip-address: true #使用ip地址注册到注册中心
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册中心列表中显示的状态参数

ribbon:
  ReadTimeout: 15000  #建立连接超时时间
  ConnectTimeout: 15000  #读取资源超时间

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds:  15000

management:
  endpoint:
    health:
      show-details: always

#netty-websocket:
#  host: 0.0.0.0
#  path: /ws
#  port: 18092
logging:
  enable-api-log: false
