server:
  #服务端口号
  port: 8082

spring:
  application:
    name: cms-cloud-gateway  #服务名称 - 服务之间使用名称进行通讯
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: microservice-base
          uri: lb://microservice-base/
          predicates:
            - Path= /microservice-base/**
        - id: microservice-job
          uri: lb://microservice-job/
          predicates:
            - Path= /microservice-job/**

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka #填写注册中心服务器地址
    register-with-eureka: true  #是否需要将自己注册到注册中心
    fetch-registry: true  #是否需要搜索服务信息
  instance:
    prefer-ip-address: true #使用ip地址注册到注册中心
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册中心列表中显示的状态参数