cms:
  defaultValue:
    pageNum: 1
    pageSize: 30
server:
  port: 8084  #服务端口配置

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #数据源配置
    url: jdbc:mysql://127.0.0.1:3306/ms_job_db?serverTimezone=Asia/Shanghai
    username: root
    password: mn@123456!
    type: com.alibaba.druid.pool.DruidDataSource  #连接池配置
    max-idle: 10  #No operations allowed after connection closed错误原因及解决
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
  profiles:
    active: dao
  application:
    name: microservice-job #服务名称-服务之间使用名称进行通讯

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka #填写注册中心服务器地址
    register-with-eureka: true  #是否需要将自己注册到注册中心
    fetch-registry: true  #是否需要搜索服务信息
  instance:
    prefer-ip-address: true #使用ip地址注册到注册中心
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册中心列表中显示的状态参数

ribbon:
  ReadTimeout: 15000  #建立连接超时时间
  ConnectTimeout: 15000  #读取资源超时间

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds:  15000

management:
  endpoint:
    health:
      show-details: always